# Generated by Django 5.0.6 on 2024-06-04 17:04

import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('appetizer', 'Appetizer'), ('soup', 'Soup'), ('salad', 'Salad'), ('main', 'Main dishes'), ('pasta', 'Pasta/Noodles'), ('rice', 'Rice/Grains'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('seafood', 'Seafood'), ('meat', 'Meat'), ('pizza', 'Pizza'), ('sandwich', 'Sandwich/Wraps'), ('side', 'Side dishes'), ('breakfast/brunch', 'Breakfast/Bruch'), ('dessert', 'Desserts'), ('grill', 'Grilling/Barbecue'), ('healthy', 'Healthy/Low calories'), ('international', 'International Cuisine')], default=None, max_length=255, null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default=None, max_length=255, null=True)),
                ('cooking_time', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
